### ISSUE TITLE
Some uncritical build warnings

### ISSUE THREAD

**Issue by tsufz** [schymane/RChemMass#1]
Hi Emma,
here are some smaller errors during the build of RChemMass
Downloading GitHub repo schymane/RChemMass@master
from URL https://api.github.com/repos/schymane/RChemMass/zipball/master
Installing RChemMass
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e"  \
  --library="C:/R/win-library/3.2" --install-tests 

* installing *source* package 'RChemMass' ...
** R
Warning: unable to re-encode 'CompTox.R' lines 96, 133
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'RChemMass'
    finding HTML links ... done
    CAS_fix                                 html  
    CAS_test                                html  
    InChIKey_test                           html  
    MolFormFromInChI                        html  
    MolFormFromSmiles.rcdk                  html  
    finding level-2 HTML links ... done

    RtoSMILES                               html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/RtoSMILES.Rd:45: missing link 'BuildSmiles'
    adjustRgroup                            html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/adjustRgroup.Rd:63: missing link 'BuildSmiles'
    build.homol                             html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/build.homol.Rd:34: missing link 'RMassBank'
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/build.homol.Rd:50: missing link 'BuildSmiles'
    build.homol.byMass                      html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/build.homol.byMass.Rd:51: missing link 'screen.homol'
    buildCDKdepictURL                       html  
    buildCompToxURL                         html  
    buildMemberLabels                       html  
    buildSeriesLabel                        html  
    buildSmiles                             html  
    check_ded2                              html  
    getAdductMassesFromFormula              html  
    getCDKlogPs                             html  
    getCDKlogPsAndRT                        html  
    getInChIKey.obabel                      html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getInChIKey.obabel.Rd:20: missing link 'http://openbabel.org/wiki/Main_Page'
    getSmilesFromInChI.babel                html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSmilesFromInChI.babel.Rd:21: missing link 'http://openbabel.org/wiki/Main_Page'
    getSuspectFormulaMass                   html  
    getSuspectIdentifiers                   html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectIdentifiers.Rd:26: missing link 'getPcID'
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectIdentifiers.Rd:27: missing link 'https://pubchem.ncbi.nlm.nih.gov/'
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectIdentifiers.Rd:28: missing link 'http://www.chemspider.com/'
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectIdentifiers.Rd:30: missing link 'https://cactus.nci.nih.gov/chemical/structure'
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectIdentifiers.Rd:32: missing link 'http://cts.fiehnlab.ucdavis.edu/'
    getSuspectInChIKey                      html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectInChIKey.Rd:19: missing link 'https://cactus.nci.nih.gov/chemical/structure'
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectInChIKey.Rd:21: missing link 'http://cts.fiehnlab.ucdavis.edu/'
    getSuspectInChIKey.babel                html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/getSuspectInChIKey.babel.Rd:22: missing link 'http://openbabel.org/wiki/Main_Page'
    getSuspectMasses                        html  
    renderSMILES.CDKdepict                  html  
    renderSMILES.rcdk                       html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/renderSMILES.rcdk.Rd:64: missing link 'https://github.com/rajarshi/cdkr/issues/49'
    renderSMILES.rcdk.default               html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/renderSMILES.rcdk.default.Rd:32: missing link 'https://github.com/rajarshi/cdkr/issues/49'
    splitRrange                             html  
    trimBuiltSmiles                         html  
Rd warning: C:/Users/schulzet/AppData/Local/Temp/Rtmp0Eno6Q/devtools2dc6b126a5d/schymane-RChemMass-d3d304e/man/trimBuiltSmiles.Rd:29: missing link 'BuildSmiles'
    trimKey                                 html  

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.5

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.5.0 R6_2.2.2       tools_3.5.0    withr_2.1.2    rstudioapi_0.7 curl_3.2      
 [8] yaml_2.1.18    memoise_1.1.0  git2r_0.21.0   digest_0.6.15

**Comment by schymane** [comment]
These are all warnings not errors?
