### ISSUE TITLE
check_ded2 should not die on deducting nothing

### ISSUE THREAD

**Issue by MaliRemorker** [schymane/RChemMass#10]
##### Problem
```check_ded2('CO2','')```
> Error in grep(element, formula_elements) : invalid 'pattern' argument

##### Session Info (just in case):

> sessionInfo()

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-unknown-linux-gnu (64-bit)
> Running under: Pop!_OS 20.04 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /gnu/store/vax1vsg3ivf0r7j7n2xkbi1z3r0504l9-openblas-0.3.7/lib/libopenblasp-r0.3.7.so
> 
> locale:
>  [1] LC_CTYPE=en_GB.UTF-8          LC_NUMERIC=C                 
>  [3] LC_TIME=en_GB.UTF-8           LC_COLLATE=en_GB.UTF-8       
>  [5] LC_MONETARY=de_DE.UTF-8       LC_MESSAGES=en_GB.UTF-8      
>  [7] LC_PAPER=de_DE.UTF-8          LC_NAME=en_GB.UTF-8          
>  [9] LC_ADDRESS=en_GB.UTF-8        LC_TELEPHONE=en_GB.UTF-8     
> [11] LC_MEASUREMENT=de_DE.UTF-8    LC_IDENTIFICATION=en_GB.UTF-8
> 
> attached base packages:
> [1] grid      stats     graphics  grDevices utils     datasets  methods  
> [8] base     
> 
> other attached packages:
>  [1] ReSOLUTION_0.1.8   nontarget_2.1      mgcv_1.8-31        nlme_3.1-145      
>  [5] nontargetData_1.1  mzR_2.20.0         readxl_1.3.1       OrgMassSpecR_0.5-3
>  [9] RChemMass_0.1.23   RCurl_1.95-0.1.2   bitops_1.0-6       rjson_0.2.20      
> [13] rsvg_1.3           curl_4.3           rcdk_3.4.3         rcdklibs_2.0      
> [17] rJava_0.9-12       RMassBank_2.14.1   Rcpp_1.0.4         enviPat_2.4       
> 
> loaded via a namespace (and not attached):
>  [1] ProtGenerics_1.18.0   doParallel_1.0.15     MSnbase_2.12.0       
>  [4] tools_3.6.3           R6_2.4.1              affyio_1.56.0        
>  [7] BiocGenerics_0.32.0   colorspace_1.4-1      tidyselect_1.0.0     
> [10] compiler_3.6.3        preprocessCore_1.48.0 cli_2.0.2            
> [13] Biobase_2.46.0        scales_1.1.0          affy_1.64.0          
> [16] digest_0.6.25         pkgconfig_2.0.3       htmltools_0.4.0      
> [19] fastmap_1.0.1         itertools_0.1-3       limma_3.42.2         
> [22] rlang_0.4.5           impute_1.60.0         shiny_1.4.0.2        
> [25] mzID_1.24.0           BiocParallel_1.20.1   dplyr_0.8.5          
> [28] magrittr_1.5          MALDIquant_1.19.3     Matrix_1.2-18        
> [31] munsell_0.5.0         S4Vectors_0.24.3      fansi_0.4.1          
> [34] lifecycle_0.2.0       vsn_3.54.0            yaml_2.2.1           
> [37] MASS_7.3-51.5         zlibbioc_1.32.0       plyr_1.8.6           
> [40] parallel_3.6.3        promises_1.1.0        crayon_1.3.4         
> [43] lattice_0.20-40       splines_3.6.3         pillar_1.4.3         
> [46] shinyscreen_0.9.0     codetools_0.2-16      stats4_3.6.3         
> [49] XML_3.99-0.3          glue_1.3.2            pcaMethods_1.78.0    
> [52] data.table_1.12.8     BiocManager_1.30.10   png_0.1-7            
> [55] vctrs_0.2.4           httpuv_1.5.2          foreach_1.5.0        
> [58] cellranger_1.1.0      gtable_0.3.0          purrr_0.3.3          
> [61] assertthat_0.2.1      ggplot2_3.3.0         mime_0.9             
> [64] xtable_1.8-4          later_1.0.0           ncdf4_1.17           
> [67] tibble_3.0.0          iterators_1.0.12      fingerprint_3.5.7    
> [70] IRanges_2.20.2        ellipsis_0.3.0

**Comment by schymane** [comment]
So the question is in that case ... should it return `TRUE` or `FALSE`?
Since an empty input could, by default, always be deducted I guess `TRUE`?
