### ISSUE TITLE
consider adding a CITATION file

### ISSUE THREAD

**Issue by egonw** [schymane/RChemMass#7]

**Comment by schymane** [comment]
Not yet published, on my far too long to-do list ... (or what else could one put to cite it? I put it in as a URL pointing to the github repo)

**Comment by egonw** [comment]
The `CITATION` file can have BibTeX for `@unpublished` too, see https://astrostatistics.psu.edu/su07/R/html/utils/html/citEntry.html

**Comment by egonw** [comment]
or `@misc`
